### ISSUE TITLE
Spread gate filter for the GOA and AI

### ISSUE THREAD

**Issue by sean-rohan-NOAA** [afsc-gap-products/postsurvey_hauldata_processing#12]
### Question
@Ned-Laman-NOAA What is the default range for gating spread data in the GOA and AI? As an example, in the EBS we reject spread values that are not between 10 and 22 m.

**Comment by Ned-Laman-NOAA** [comment]
8-22 m for spread in the Gulf and Aleutians, 3-10 m for height

**Comment by sean-rohan-NOAA** [comment]
Thank you
